### ISSUE TITLE
Can we bold/make the point ‘stand out’ that we aren’t asking for personal information? 

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/forum#9] opened 2015-01-08 11:58 UTC
Moved here from https://github.com/OpenAddressesUK/theodolite/issues/44 : 

> Vision Last paragraph- can we bold/make the point ‘stand out’ that we aren’t asking for personal information? This is an important point to make and I think it gets lost in the paragraph 1.	Team Biographies possibly still too long? Jeni- include Sir (Tim Berners-Lee) Dr Mike Sanderson- his photo is pixilated and need to upload a higher quality picture Peter- upload an image 2.	How it works- Technology Graph- can we make this graph open up in a new window ‘decided to ignore addresses’- could be rephrased to ‘not include’? 3.	How it works- adding data ‘To be written’ could be rephrased to say ‘coming soon’ Links Can you make the links embedded into the text open up into a new page? From personal experience I know how frustrating it can be trying to find my way back to the page I was originally viewing.

**Comment by peterkwells** [comment] 2015-03-10 15:03
Closing duplicate of https://github.com/OpenAddressesUK/forum/issues/33

**Closed by peterkwells** 2015-03-10 15:03 UTC
Labels: feature requests
